name: redis-server
title: Redis Server
version: 7.2.0-v6
summary: Redis Server for ctrlX
description: |
    Redis (Remote Dictionary Server) is an open-source in-memory storage, used as a distributed, in-memory key–value database, cache and message broker, with optional durability. Because it holds all data in memory and because of its design, Redis offers low-latency reads and writes, making it particularly suitable for use cases that require a cache.     

architectures:
    - arm64
grade: stable
confinement: strict
base: core22
type: app

apps:
    redis-server:
        command: launcher.sh
        daemon: simple
        restart-condition: always
        plugs: [network, network-bind]
        passthrough:
            restart-delay: 10s

    cli:
        command: usr/bin/redis-cli
        plugs: [home, network]

parts:
    redis-server:
        source: https://download.redis.io/redis-stable.tar.gz
        plugin: dump
        override-build:
            make redis-server redis-cli
        organize:
            ../build/src/redis-server: usr/bin/
            ../build/src/redis-cli: usr/bin/	    
        stage:
            - usr/bin/redis-server
            - usr/bin/redis-cli	    
        stage-packages:
            - libssl-dev

    script:
        plugin: dump
        source: snap/local
        prime:      
          - launcher.sh

    configs:
        plugin: dump
        source: ./configs
        organize:
            'package-assets/*': package-assets/${SNAPCRAFT_PROJECT_NAME}/
        stage:
            - default_config.conf


plugs:
    redis-server-home:
        interface: home
        stage-packages: [libssl-dev, libomp1]
    redis-server-network:
        interface: network
    active-solution:
        interface: content
        content: solutions
        target: $SNAP_DATA/solutions